### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by NCUIui** [dirkiedai/sk-mt#3]

**Comment by atspring178** [comment]
I use: pytorch=1.12.0, elasticsearch=8.6.1, fairseq

**Comment by dirkiedai** [comment]
Hello, there!

It seems that you missed a "\\" after each line of the python command, therefore all the arguments are not correctly parsed. How about trying this:

python $PROJECT_PATH/bm25_retrieval.py \\
                        --build_index --search_index \\
                        --index_file $DATA_PATH/train.txt \\
                        --search_file $DATA_PATH/$type.txt \\
                        --output_file $DATA_PATH/$domain.$type \\
                        --index_name $domain --topk 64

**Comment by atspring178** [comment]
OK, thank you very much. This problem is solved, 
but "TypeError: __init__() missing 1 required positional argument: 'scheme' " appears during runtime.
 I modify es = Elasticsearch([{u'host': "localhost", u'port': "9200"}], timeout=30) is: es = Elasticsearch([{u'host': "localhost", u'port': 9200,u'scheme': "http"}], timeout=30): elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))
How can we solve it correctly?Thanks!

**Comment by NCUIui** [comment]
When configuring the environment, I passed ：“wget -c https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.6.1-linux-x86_64.tar.gz”, then “pip install elasticsearch==8.6.1”, and executed Before retrieval, also start elastic search service on port 9200 through“ ./elasticsearch-8.6.1/bin/elasticsearch”
